library(tidyr)
available_srs <- c("销售代表1",
                   "销售代表2",
                   "销售代表3",
                   "销售代表4",
                   "销售代表5")




pp_info_by_hosp_product <- list(
                 hospital1 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital2 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital3 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital4 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital5 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital6 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital7 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital8 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital9 = list(product1 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product2 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product3 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50),
                                  product4 = list(pp_sales = 100000,
                                                  sr_sales_performance = 60,
                                                  deployment_quality = 50,
                                                  customer_relationship = 50,
                                                  promotional_support = 50,
                                                  sales_performance = 50,
                                                  offer_attractiveness = 50)),
                 hospital10 = list(product1 = list(pp_sales = 100000,
                                                   sr_sales_performance = 60,
                                                   deployment_quality = 50,
                                                   customer_relationship = 50,
                                                   promotional_support = 50,
                                                   sales_performance = 50,
                                                   offer_attractiveness = 50),
                                   product2 = list(pp_sales = 100000,
                                                   sr_sales_performance = 60,
                                                   deployment_quality = 50,
                                                   customer_relationship = 50,
                                                   promotional_support = 50,
                                                   sales_performance = 50,
                                                   offer_attractiveness = 50),
                                   product3 = list(pp_sales = 100000,
                                                   sr_sales_performance = 60,
                                                   deployment_quality = 50,
                                                   customer_relationship = 50,
                                                   promotional_support = 50,
                                                   sales_performance = 50,
                                                   offer_attractiveness = 50),
                                   product4 = list(pp_sales = 100000,
                                                   sr_sales_performance = 60,
                                                   deployment_quality = 50,
                                                   customer_relationship = 50,
                                                   promotional_support = 50,
                                                   sales_performance = 50,
                                                   offer_attractiveness = 50)))


pp_info_by_hosp_product_m <- unlist(pp_info_by_hosp_product, recursive = 
                                      FALSE)
pp_info_by_hosp_product_m <-
  do.call("rbind", pp_info_by_hosp_product_m) %>%
  as.data.frame(., stringsAsFactors = FALSE) %>%
  mutate(tmp = rownames(.)) %>%
  separate(tmp, c("hospital", "product"))

pp_info_by_hosp_product_m1 <- pp_info_by_hosp_product_m %>%
  select(-c(pp_sales,hospital,product))
colnames(pp_info_by_hosp_product_m1) <- paste("pp_",colnames(pp_info_by_hosp_product_m1),sep="")
colnames(pp_info_by_hosp_product_m1)[2:4] <- paste(colnames(pp_info_by_hosp_product_m1)[2:4],"_index",sep="")
colnames(pp_info_by_hosp_product_m1)[6] <- paste(colnames(pp_info_by_hosp_product_m1)[6],"_index",sep="")

pp_info_by_hosp_product_m2 <- pp_info_by_hosp_product_m %>%
  select(pp_sales,hospital,product)

pp_info_by_hosp_product_new <- data.frame(
  pp_info_by_hosp_product_m1,
  pp_info_by_hosp_product_m2
)



real_sales <- seq(50000,150000,1000)

real_sales_product1 <- list(hospital1 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital2 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital3 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital4 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital5 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital6 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital7 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital8 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital9 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital10 = list(phase1 = sample(real_sales,1),
                                              phase2 = sample(real_sales,1),
                                              phase3 = sample(real_sales,1),
                                              phase4 = sample(real_sales,1)))
real_sales_product2 <- list(hospital1 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital2 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital3 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital4 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital5 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital6 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital7 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital8 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital9 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital10 = list(phase1 = sample(real_sales,1),
                                              phase2 = sample(real_sales,1),
                                              phase3 = sample(real_sales,1),
                                              phase4 = sample(real_sales,1)))

real_sales_product3 <- list(hospital1 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital2 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital3 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital4 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital5 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital6 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital7 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital8 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital9 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital10 = list(phase1 = sample(real_sales,1),
                                              phase2 = sample(real_sales,1),
                                              phase3 = sample(real_sales,1),
                                              phase4 = sample(real_sales,1)))

real_sales_product4 <- list(hospital1 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital2 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital3 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital4 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital5 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital6 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital7 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital8 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital9 = list(phase1 = sample(real_sales,1),
                                             phase2 = sample(real_sales,1),
                                             phase3 = sample(real_sales,1),
                                             phase4 = sample(real_sales,1)),
                            hospital10 = list(phase1 = sample(real_sales,1),
                                              phase2 = sample(real_sales,1),
                                              phase3 = sample(real_sales,1),
                                              phase4 = sample(real_sales,1)))
sr_info_initial <-
  data.frame(sales_name = c("销售代表1",
                            "销售代表2",
                            "销售代表3",
                            "销售代表4",
                            "销售代表5"),
             sales_skills = c("Advanced/Experienced",
                              "skilled",
                              "skilled",
                              "Advanced",
                              "Expert"),
             product_knowledge = c("Advanced/Expert",
                                   "Advanced",
                                   "Fundamental",
                                   "Skilled",
                                   "Advanced"),
             motivation = c("low",
                            "high",
                            "high",
                            "middle",
                            "high")
             )

sr_info_initial_value <-
  data.frame(sales_rep = c("销售代表1",
                            "销售代表2",
                            "销售代表3",
                            "销售代表4",
                            "销售代表5"),
             sales_level = c("middle",
                             "junior",
                             "junior",
                             "middle",
                             "senior"),
             pp_acc_revenue = c(1800000,
                             1000000,
                             1200000,
                             1500000,
                             2500000),
             pp_sales_skills_index = c(3,2,2,3,5),
             pp_product_knowledge_index = c(20,15,5,10,15),
             pp_motivation_index = c(20,60,60,40,60),
             pp_acc_field_work = rep(0,5))

sr_info_initial_value$sales_rep <- as.character(sr_info_initial_value$sales_rep)
sr_info_initial_value$sales_level <- as.character(sr_info_initial_value$sales_level)

product_info_initial <-
  data.frame(product = c("Tube Feed",
                         "Oral Nutritional Supplement(ONS)",
                         "Disease Specific Product1",
                         "Pediatric product"),
             name2= c("product1",
                      "product2",
                      "product3",
                      "product4"),
             name = c("NutroSource",
                      "NutroDrink",
                      "Peptasource",
                      "Peptasource Junior"),
             Volume = c("High Volume",
                        "High Volume",
                        "Low-Middle Volume",
                        "Low Volume"),
             margin = c("Low Margin",
                        "Low Margin",
                        "High Margin",
                        "High Margin"))


hospital_info_initial <- 
  data.frame(hospital = c("calgary",
                      "barcelona",
                      "Manchester",
                      "Rome",
                      "Paris",
                      "Toronto",
                      "colmbia",
                      "New Delhi",
                      "sydney",
                      "Sao Paulo"),
             name = c("hospital1",
                      "hospital2",
                      "hospital3",
                      "hospital4",
                      "hospital5",
                      "hospital6",
                      "hospital7",
                      "hospital8",
                      "hospital9",
                      "hospital10"),
             type = c("children",
                      "university",
                      "community",
                      "community",
                      "children",
                      "university",
                      "community",
                      "university",
                      "children",
                      "university"),
             beds = c(150,
                      510,
                      375,
                      250,
                      110,
                      770,
                      385,
                      415,
                      200,
                      425))

weightage <- list(total_attractiveness = list(pp_offer_attractiveness = 0.35,
                                              cp_offer_attractiveness = 0.65),
                  cp_offer_attractiveness = list(sales_performance = 0.6,
                                                 customer_relationship = 0.4),
                  sales_performance = list(sr_sales_performance = 0.6,
                                           field_work = 0.05,
                                           deployment_quality = 0.35),
                  customer_relaitonship = list(product_knowledge = 0.05,
                                               promotional_support = 0.15,
                                               past_relationship = 0.8),
                  sr_sales_performance = list(motivation = 0.15,
                                              sales_skills = 0.3,
                                              product_knowledge = 0.05,
                                              time_with_account = 0.5),
                  deployment_quality = list(strategy_and_cycle_planning = 0.15,
                                            kpi_report_analysis =0.1,
                                            admin_work = 0.1,
                                            meetings_with_team = 0.1,
                                            priority_fit = 0.55),
                  promotional_support = list(promotional_budget = 0.65,
                                             strategy_and_cycle_planning = 0.35),
                  sales_skills = list(field_work = 0.2,
                                      sales_training = 0.3,
                                      experience = 0.5),
                  motivation = list(admin_work = 0.1,
                                    sales_target_realization =0.4,
                                    meetings_with_team = 0.25,
                                    sales_training = 0.25),
                  success_value = list(total_sales = 0.3,
                                       contribution_margin = 0.4,
                                       average_customer_relationship = 0.09,
                                       average_sales_skills = 0.07,
                                       average_product_knowledge = 0.07,
                                       average_motivaiton = 0.07))

total_promotional_budget <- list(phase1 = 10000,
                                 phase2 = 10000,
                                 phase3 = 10000,
                                 phase4 = 10000)

potential_sales_product1 <- list(hospital1 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital2 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital3 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital4 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital5 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital6 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital7 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital8 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital9 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital10 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000)
                                 )

potential_sales_product2 <- list(hospital1 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital2 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital3 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital4 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital5 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital6 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital7 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital8 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital9 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital10 = list(phase1 = 100000,
                                                   phase2 = 100000,
                                                   phase3 = 100000,
                                                   phase4 = 100000)
)
potential_sales_product3 <- list(hospital1 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital2 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital3 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital4 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital5 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital6 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital7 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital8 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital9 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital10 = list(phase1 = 100000,
                                                   phase2 = 100000,
                                                   phase3 = 100000,
                                                   phase4 = 100000)
)
potential_sales_product4 <- list(hospital1 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital2 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital3 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital4 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital5 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital6 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital7 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital8 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital9 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital10 = list(phase1 = 100000,
                                                   phase2 = 100000,
                                                   phase3 = 100000,
                                                   phase4 = 100000)
)

current_sales_product1 <- list(hospital1 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital2 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital3 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital4 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital5 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital6 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital7 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital8 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital9 = list(phase1 = 100000,
                                                  phase2 = 100000,
                                                  phase3 = 100000,
                                                  phase4 = 100000),
                                 hospital10 = list(phase1 = 100000,
                                                   phase2 = 100000,
                                                   phase3 = 100000,
                                                   phase4 = 100000)
)

current_sales_product2 <- list(hospital1 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital2 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital3 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital4 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital5 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital6 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital7 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital8 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital9 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital10 = list(phase1 = 100000,
                                                 phase2 = 100000,
                                                 phase3 = 100000,
                                                 phase4 = 100000)
)

current_sales_product3 <- list(hospital1 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital2 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital3 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital4 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital5 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital6 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital7 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital8 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital9 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital10 = list(phase1 = 100000,
                                                 phase2 = 100000,
                                                 phase3 = 100000,
                                                 phase4 = 100000)
)

current_sales_product4 <- list(hospital1 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital2 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital3 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital4 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital5 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital6 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital7 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital8 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital9 = list(phase1 = 100000,
                                                phase2 = 100000,
                                                phase3 = 100000,
                                                phase4 = 100000),
                               hospital10 = list(phase1 = 100000,
                                                 phase2 = 100000,
                                                 phase3 = 100000,
                                                 phase4 = 100000)
)


###
worktime =100
overhead =2
basicSalary = 15000

