---
title: "销售培训平台详解"
author:
  - 陈安琪
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    #toc: yes
classoption: "hyperref,"
---

# 平台介绍

这是一个提供给销售经理用于在线拓展销售管理能力的平台，销售经理通过模拟一年四个季度（周期）的客户维护与员工培训决策，得到各季度报告以及最后的综合得分；经过不断的在线训练，提高综合得分，增强决策能力与地区管理能力。

# 报告详解

##代表报告
- **职员成本**: 总薪酬 
    + 基本薪酬(预设) 
    + 奖金(与销售指标完成情况相关curve10)
- **时间分配报告**: 工作时间(预设) 
    + 日常事物 
    + 产品培训 
    + 销售培训 
    + 团队会议 
    + 医院拜访
- **产品知识**： 当期产品知识
    + 上期产品知识的过渡值(curve28) 
    + 当期产品培训产生的额外值(curve26)
- **经验**: 当期经验 = 销售代表的累计销售额(curve11)
- **销售技巧**：当期销售技巧
    + 累计经理随访*权重
    + 销售培训经验(curve43)*权重 
    + 上期经验(curve44)*权重
- **动力值**：当期动力值
    + 行政工作(curve18)
    + 销售指标完成情况(curve16)
    + 团队会议(curve15)
    + 销售培训(curve17)




##经理报告
- **职员成本**：总薪酬 = 所有销售代表薪酬之和
- **时间分配**：总时间分配(预设)
    + 销售培训
    + 医院拜访
    + 团队会议
    + KPI分析
    + 战略和周期计划
    + 行政工作  


##分配报告(各医院)
- **计划时间分配**：输入值
- **实际时间分配**：计划时间分配 - 日常事物(overhead time)

##决策报告(各医院)
- **总体分配情况**：各医院 对应 分配的销售代表
- **分级匹配度**：
    + A级客户分配时间
    + B级客户分配时间
    + C级客户分配时间
    + D级客户分配时间
    + 总分级匹配度(各级客户匹配度*权重然后求和)
- **决策质量**：当期决策质量(deployment quality)
    + 行政工作(curve5)*权重
    + 分级匹配度(curve6)*权重
    + 团队会议(curve7)*权重
    + KPI分析(curve8)*权重
    + 战略和周期计划(curve9)*权重

##利润贡献(总体)
- **利润贡献I(每产品)** 
    + 销售数量：潜力销售数量 \* (1+volume factor) 与上期sales performance相关curve31
    + 销售额：每件价格*潜力销售数量 
    + 生产成本：每件生产成本(预设) * 销售数量
    + 利润贡献I：销售额-生产成本
- **利润贡献III(总体)**
    + 生产成本：所有产品生产成本之和
    + 利润贡献I：销售额-生产成本
    + 其他可变成本：折扣花费 + 推广费用
    + 利润贡献II：利润贡献I - 其他可变成本
    + 利润贡献III：利润贡献II - 员工薪酬 - 总体行政花销(预设权重)
    
##利润贡献(各医院)
- **销售额**
- **生产成本**
- **推广费用预算**
- **其他可变成本**
- **利润贡献II**

##销售报告
- **销售额增长**
- **销售额增长率**

##市场调研报告
- **商业价值**
    + 总销售额
    + 总利润贡献III
    + 客户关系平均水平
    + 平均销售技巧水平
    + 平均产品知识水平
    + 平均动力值
    + 商业价值(offer attractiveness) =  客户关系、折扣、销售表现、
- **总市场概述(各医院)**
    + 总销售
    + 总市场份额

